filter:
    excluded_paths:
        - "attachments/*"
        - "avatars/*"
        - "cache/*"
        - "docs/*"
        - "packages/*"
        - "smileys/*"
        - "tests/*"
        - "ext/*"
        - "sources/ext/*"
        - "install/*"
        - "languages/*"
        - themes/default/scripts/jquery-3.1.1.min.js
        - themes/default/scripts/jquery.atwho.min.js
        - themes/default/scripts/jquery.caret.min.js
        - themes/default/scripts/jquery.sceditor.bbcode.min.js
        - themes/default/scripts/jquery.sceditor.min.js
        - themes/default/scripts/undo.plugin.min.js
        - themes/default/scripts/jquery-ui-1.12.1.min.js
        - themes/default/scripts/prettify.min.js
        - themes/default/scripts/sha256.js
        - themes/default/scripts/qrcode.js
        - themes/default/scripts/favico.js
tools:
    external_code_coverage:
        timeout: 1800
        runs: 4
    js_hint:
        filter:
            excluded_paths: ['attachments/*', 'avatars/*', 'cache/*', 'docs/*', 'packages/*', 'smileys/*', 'tests/*', 'sources/ext/*', 'ext/*', 'themes/default/scripts/jquery2.1.4.min.js', 'themes/default/scripts/jquery.atwho.min.js','themes/default/scripts/jquery.caret.min.js','themes/default/scripts/jquery.sceditor.bbcode.min.js','themes/default/scripts/jquery.sceditor.min.js','themes/default/scripts/jquery-ui-1.11.4.min.js','themes/default/scripts/qrcode.js','themes/default/scripts/prettify.min.js','themes/default/undo.plugin.min.js','themes/default/scripts/sha256.js']
checks:
    php:
        verify_property_names: true
        verify_argument_usable_as_reference: true
        verify_access_scope_valid: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        too_many_arguments: true
        switch_fallthrough_commented: true
        sql_injection_vulnerabilities: true
        single_namespace_per_use: true
        simplify_boolean_return: true
        security_vulnerabilities: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_php_tag_first: true
        remove_extra_empty_lines: true
        psr2_switch_declaration: true
        psr2_class_declaration: true
        property_assignments: true
        prefer_while_loop_over_for_loop: true
        precedence_mistakes: true
        precedence_in_conditions: true
        phpunit_assertions: true
        php5_style_constructor: true
        parse_doc_comments: true
        parameter_non_unique: true
        parameter_doc_comments: true
        overriding_private_members: true
        optional_parameters_at_the_end: true
        non_commented_empty_catch_block: true
        no_unnecessary_if: true
        no_unnecessary_final_modifier: true
        no_trailing_whitespace: true
        no_short_open_tag: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        no_goto: true
        no_empty_statements: true
        no_duplicate_arguments: true
        no_debug_code: true
        more_specific_types_in_doc_comments: true
        missing_arguments: true
        method_calls_on_non_object: true
        instanceof_class_exists: true
        foreach_usable_as_reference: true
        foreach_traversable: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: false
        fix_doc_comments: true
        encourage_single_quotes: true
        encourage_shallow_comparison: true
        encourage_postdec_operator: true
        duplication: true
        deadlock_detection_in_loops: true
        code_rating: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        catch_class_exists: true
        blank_line_after_namespace_declaration: true
        avoid_useless_overridden_methods: true
        avoid_usage_of_logical_operators: true
        avoid_unnecessary_concatenation: true
        avoid_superglobals: false
        avoid_multiple_statements_on_same_line: true
        avoid_length_functions_in_loops: true
        avoid_duplicate_types: false
        avoid_corrupting_byteorder_marks: true
        avoid_conflicting_incrementers: true
        avoid_closing_tag: true
        avoid_aliased_php_functions: true
        assignment_of_null_return: true
        argument_type_checks: true
        align_assignments: true
        one_class_per_file: false
        line_length:
            max_length: '150'
        no_commented_out_code: false
    javascript:
        vars_on_top: true
        valid_typeof: true
        use_isnan: true
        radix: true
        one_var: true
        no_unused_vars: true
        no_unreachable: true
        no_undefined: true
        no_trailing_spaces: true
        no_ternary: true
        no_sparse_arrays: true
        no_shadow: true
        no_self_compare: true
        no_reserved_keys: true
        no_redeclare: true
        no_nested_ternary: true
        no_negated_in_lhs: true
        no_mixed_spaces_and_tabs: true
        no_loop_func: true
        no_lonely_if: true
        no_lone_blocks: true
        no_irregular_whitespace: true
        no_inner_declarations: true
        no_extra_semi: true
        no_extra_boolean_cast: true
        no_else_return: true
        no_dupe_keys: true
        no_debugger: true
        no_console: true
        no_comma_dangle: true
        no_alert: true
        eqeqeq: true
        var_sometimes_initialized: false
        nsp_vulnerabilities: false
        curly: false
        new_cap: false

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: true
        braces:
            classes_functions:
                class: new-line
                function: new-line
            if:
                always: false
                else_on_new_line: true
            for:
                always: false
            while:
                always: false
            do_while:
                opening: new-line
            switch:
                opening: new-line
            try:
                opening: new-line
                catch_on_new_line: true
                finally_on_new_line: true
